Добавила загрузку профиля
lkorasik/Ktista pull request #125
Opened 2021-12-12 12:40 UTC by AlibabaRazboinik

2021-12-12 20:58 UTC, obduvan commented on KtistaClient/app/src/main/java/com/lkorasik/ktistaclient/ui/profile/ProfileFragment.kt
> +    private lateinit var rootActivity: MainActivity
Зачем он нужен?

2021-12-12 20:58 UTC, obduvan commented on KtistaClient/app/src/main/java/com/lkorasik/ktistaclient/ui/profile/ProfileFragment.kt
> +        viewModel.data.observe(this, {
настраивай вьюмодель в одном месте в коде
или логично компоновать все что связано с установкой обзерверов и инициализацией вьюмодели

2021-12-12 20:58 UTC, obduvan commented on KtistaClient/app/src/main/java/com/lkorasik/ktistaclient/ui/profile/ProfileViewModel.kt
> +    val data = MutableLiveData(ProfileResponse(""))
Зачем здесь нужен пустой объект?

2021-12-13 06:07 UTC, AlibabaRazboinik commented on KtistaClient/app/src/main/java/com/lkorasik/ktistaclient/ui/profile/ProfileViewModel.kt
> +    val data = MutableLiveData(ProfileResponse(""))
Когда придет ответ с сервера данные будут хранится в этом поле

2021-12-13 06:08 UTC, AlibabaRazboinik commented on KtistaClient/app/src/main/java/com/lkorasik/ktistaclient/ui/profile/ProfileViewModel.kt
> +    val data = MutableLiveData(ProfileResponse(""))
Смотри выше, где создается ProfileRequest

2021-12-13 09:36 UTC, obduvan requested changes

2021-12-13 09:36 UTC, obduvan commented on KtistaClient/app/src/main/java/com/lkorasik/ktistaclient/ui/profile/ProfileViewModel.kt
> +    val data = MutableLiveData(ProfileResponse(""))
val data = MutableLiveData<ProfileResponse>()
и проверить на что obj != null

2021-12-14 13:16 UTC, obduvan approved these changes

2021-12-14 13:17 UTC, merged