Добавил виджет подписки
lkorasik/Ktista pull request #60
Opened 2021-10-31 15:35 UTC by lkorasik

Думаю, что виджет отписки будет использовать ту же разметку, только надо будет из кода поменять текст и стиль кнопки.

2021-10-31 16:33 UTC, obduvan commented
Делай плиз как фигме)
тип, уже который раз об этом пишу

2021-10-31 16:44 UTC, obduvan requested changes

2021-10-31 16:44 UTC, obduvan commented on KtistaClient/app/src/main/res/layout/fragment_subscribe.xml
> +    xmlns:android="http://schemas.android.com/apk/res/android"
Сравни с фигмой:
![image](https://user-images.githubusercontent.com/35761978/139593308-7e932ee3-eee4-40c1-8acb-a0111832ce3b.png)
![image](https://user-images.githubusercontent.com/35761978/139593333-ce66a888-c918-48a0-b4a1-6aac2776fda7.png)

2021-10-31 16:44 UTC, obduvan commented on KtistaClient/app/src/main/res/layout/fragment_subscribe.xml
> +    xmlns:android="http://schemas.android.com/apk/res/android"
Надо править пропорции

2021-10-31 16:51 UTC, lkorasik commented on KtistaClient/app/src/main/res/layout/fragment_subscribe.xml
> +    xmlns:android="http://schemas.android.com/apk/res/android"
И какая тут пропорция? Я такого в фигме не вижу

2021-10-31 16:57 UTC, obduvan commented on KtistaClient/app/src/main/res/layout/fragment_subscribe.xml
> +    xmlns:android="http://schemas.android.com/apk/res/android"
явно не 1/2 как у тебя
можно через отступы сделать
![image](https://user-images.githubusercontent.com/35761978/139594079-c8531a33-4c56-485c-8d2d-2d54700c71f5.png)

2021-10-31 16:58 UTC, obduvan commented on KtistaClient/app/src/main/res/layout/fragment_subscribe.xml
> +    xmlns:android="http://schemas.android.com/apk/res/android"
Также можно уменьшить layout_weight

2021-11-01 17:53 UTC, obduvan requested changes

2021-11-01 17:53 UTC, obduvan commented on KtistaClient/app/src/main/res/layout/fragment_subscribe.xml
>      android:layout_height="wrap_content">
мне кажется, что лучше не ставить wrap_content, лучше явно задать высоту, чтобы внутренний виджет под нее подстраивался, а не на оборот

2021-11-01 17:53 UTC, obduvan commented on KtistaClient/app/src/main/res/layout/fragment_subscribe.xml
> -        android:paddingHorizontal="@dimen/start_buttons_horizontal_padding"
Сделай хотя бы 20dp margin, иначе они очень близко будет стоять в recycleView

2021-11-01 17:53 UTC, obduvan commented
Не забудь про конфликты

2021-11-01 20:23 UTC, obduvan approved these changes

2021-11-01 20:23 UTC, merged